apiVersion: v1
kind: Service
metadata:
  name: bmp-usage-management-business-service-svc
  namespace: dtag-dev
  labels:
    app: bmp-usage-management-business-service
    version: latest
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  ports:
  - port: 18902
    nodePort: 30904
    targetPort: 8899
    protocol: TCP
  selector:
    app: bmp-usage-management-business-service
    version: latest